### ISSUE TITLE
markdown file export to pdf 

### ISSUE THREAD

**Issue by ElecRex** [marktext/marktext#1367]
When I try to make md file export to pdf, but the images couldn't show up. 

- Mark Text: v0.15.0
- Operating System: Windows 10

**Comment by Jocs** [comment]
Do you mean that Mark Text export pdf does not work?

**Comment by infeeeee** [comment]
I think I can reproduce this error, it only happens if there is a space in the image filename or in the path of the image. In the editor it shows up correctly, on pdf export it shows the markdown source of the image: `![](path to image with space.jpg)`

Also v0.15.0, win 10

**Comment by ElecRex** [comment]
> I think I can reproduce this error, it only happens if there is a space in the image filename or in the path of the image. In the editor it shows up correctly, on pdf export it shows the markdown source of the image: `![](path to image with space.jpg)`
> 
> Also v0.15.0, win 10

The images that I use are dragged into the Mark Text editor and the paths are right without any spaces.

**Comment by ElecRex** [comment]
> Can you show me you markdown file?

[demo.zip](https://github.com/marktext/marktext/files/3648020/demo.zip)

**Comment by infeeeee** [comment]
There is a space in your path... `Saved Pictures`. With Ctrl+Alt+S you can see your markdown source
![image](https://user-images.githubusercontent.com/1271737/65526982-3e4a0100-def2-11e9-8486-7218bdecd86a.png)

**Comment by fxha** [comment]
Seems to be an issue with spaces in paths in v0.15.0 which is already fixed on develop.

**Comment by ElecRex** [comment]
> There is a space in your path... `Saved Pictures`. With Ctrl+Alt+S you can see your markdown source
> ![image](https://user-images.githubusercontent.com/1271737/65526982-3e4a0100-def2-11e9-8486-7218bdecd86a.png)

Sorry, I did not see where the space is.

**Comment by DutchPete** [comment]
@infeeeee : thanks for pointing that out.
@ElecRex : @infeeeee is right about the space in the path. The way to handle that is to add %20 (not 20%) to the space in the gap. So, in your case the red part should read 
`C:\Users\lenovo\Pictures\Saved%20Pictures\400716227.jpg`

For other users: this works on Linux too.

**Comment by zachmonkey** [comment]
The export of images is still broken for both PDF and HTML on v0.16.1 for Win 10. HTML export doesn't even include the src in the tag, just an ALT, ex:

<img alt="ApocClubTestCartoonish.jpg">

**Comment by fxha** [comment]
Please see #1997 for more details. v0.16.1 has another problem with images on Windows.
