### ISSUE TITLE
config image path to relative folder but still a absolute path

### ISSUE THREAD

**Issue by ghl116** [marktext/marktext#2803]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. [First step]  configed the image preference Item "perfer relative asserts folder" to "./index_files"
2. [Second step]  clip a image  and paste to the markdown doc
3. [and so on...]   the image path is not a relative path but a absolute path.

**Expected behavior:**
 image path is  relative folder  path，like this 
[image-20211227094623573](index_files/image-20211227094623573.png

**Actual behavior:**

I configed the image preference Item "perfer relative asserts folder". But the result is still a absolute path, like this:
/private/var/folders/xf/zr2q9jy93h3cr_0ck5nr0g8w0000gn/T/WizNote/4b46d1b9-486b-402c-94ec-03767c73fee1/index_files/2021-12-27-11-04-26-image.png

**Link to an example: [optional]**

### Versions

- MarkText version: 0.16.3
- Operating system: mac

**Comment by kiyoka** [comment]
That issue has been fixed at pull request #2676.

**Comment by outer199** [comment]
+1 
Operating system: Linux

**Comment by YalandHong** [comment]
> That issue has been fixed at pull request #2676.

Yep. Dup of #2652

**Comment by VectorLu** [comment]
> > That issue has been fixed at pull request #2676.
> 
> Yep. Dup of #2652

But it seems that MarkText 0.16.3 on Windows still don't support the relative path. I have set the options like you, but it does not work.
![image](https://user-images.githubusercontent.com/12776182/147869574-56f9fd0e-9983-4dff-aca8-9d355949f6b6.png)

**Comment by fxha** [comment]
This issue was already fixed on develop and released this/next month.
