### ISSUE TITLE
Editor malfunction when operations are too fast

### ISSUE THREAD

**Issue by H16Y** [marktext/marktext#608]
### Description

- [x] Can you reproduce the issue? 

### Steps to reproduce

1. Random input with at least one line starting with "# ".
2. Using keyboard: Quickly "Ctrl+A" and then quickly press "Delete".
3. If everything is ok, try step 1 and 2 again.
4. Something weird starts to happen.

**Expected behavior:**

Everything should be normal.

**Actual behavior:**

All kinds of weird things. For example, cannot start a new line, very large space between lines, realtime preview not working, etc.

**Link to an example: [optional]**

[1.zip](https://github.com/marktext/marktext/files/2683377/1.zip)
This is a video file to demonstrate the issues. I did not use Ctrl-Z or Ctrl-Shift-Z. All undos and redos were completed through the menu (so that you can clearly know when I did that).
I am sorry that I currently have not enough time to help you find and fix the issues.

### Versions

- Mark Text: v 0.13.65
- Operating system: Windows 10 1607 x64

**Comment by fxha** [comment]
Thanks @H16Y, I can't reproduce the issue right now but we fixed a similar issue (#541) in v0.13.65. We'll definitely investigate the issue.

**Comment by H16Y** [comment]
Thanks! @fxha 
Besides, I want to provide more information below. I hope it is helpful to some extent.
The problem will be produced only when there are different levels of titles, for example, h1 (starting with one "#") and h2 (starting with two "#").
If h1 is the first line, when I press Ctrl+A, the hidden "#" before h1 titles will appear, but there is a time gap.
If I quickly press "Delete" on keyboard (before "#" appears), the problem can be produced.
It only shows how "quick" it should be to produce the issue. h1 does not have to be the first line.
I am not sure if the time gap is related to computer hardware specifications. Maybe the time gap is only long enough on slow computers?

**Comment by H16Y** [comment]
Here is an additional demonstration: @fxha 
![3](https://user-images.githubusercontent.com/45055956/50270816-cab02a80-046d-11e9-9299-8bd628d8d18c.gif)
After I deleted all the content at the first time, the first line is in format h1 by default, and I cannot start a new line by pressing `Enter`.
Then, when I pressed "#", the h1 format vanished and the text "test" appeared in the following line.
When I try to delete all the content at the last time, something I had entered before reappeared.

**Comment by fxha** [comment]
Thank you for the excellent description.

**Stack Trace:**

```
renderer.js:13 Uncaught TypeError: Cannot read property 'nodeType' of null
    at nodeType (webpack:/src/muya/lib/selection/index.js:411)
    at A.getNodeAndOffset (webpack:/src/muya/lib/selection/index.js:432)
    at A.setCursorRange (webpack:/src/muya/lib/contentState/index.js:132)
    at A.setCursor (webpack:/src/muya/lib/contentState/index.js:171)
    at A.partialRender [as inputHandler] (webpack:/src/muya/lib/contentState/inputCtrl.js:122)
    at HTMLDivElement.inputHandler (webpack:/src/muya/lib/eventHandler/keyboard.js:129)
```

Commit: a2a0363

**Comment by Jocs** [comment]
@fxha Can you still reproduce this issue with develop branch?

@H16Y Can you still reproduce this issue with v0.15.1?

**Comment by fxha** [comment]
@Jocs I cannot longer reproduce this but it was also hard to do so.

**Comment by Jocs** [comment]
It maybe fixed, because we have rewrite the `select All` menu item function.

**Comment by Jocs** [comment]
Closed due to inactive and can not reproduce, it maybe fixed, feel free to reopen it if you can reproduce.
